// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfpZTk_G7p7UGbz8e3TFBZEM5YHuy8H34',
    appId: '1:555934639780:android:e3541fee93f73692462831',
    messagingSenderId: '555934639780',
    projectId: 'tasky-82b5b',
    storageBucket: 'tasky-82b5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4gRVsr1TaAip-kk1s9Vo-k1Fz4rlP_No',
    appId: '1:555934639780:ios:8eeee7b8b306a5bf462831',
    messagingSenderId: '555934639780',
    projectId: 'tasky-82b5b',
    storageBucket: 'tasky-82b5b.firebasestorage.app',
    iosBundleId: 'com.example.tasky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4gRVsr1TaAip-kk1s9Vo-k1Fz4rlP_No',
    appId: '1:555934639780:ios:8eeee7b8b306a5bf462831',
    messagingSenderId: '555934639780',
    projectId: 'tasky-82b5b',
    storageBucket: 'tasky-82b5b.firebasestorage.app',
    iosBundleId: 'com.example.tasky',
  );
}
