// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFVVXyUOZxhSVAB-zrKxN5YNUp3opq-40',
    appId: '1:735124966094:android:d6b4bbe9b4bdb002c11e9f',
    messagingSenderId: '735124966094',
    projectId: 'tasky-app-e793e',
    storageBucket: 'tasky-app-e793e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB97okaEyeJW8h_KAOUSbNRNC9nHVje_o',
    appId: '1:735124966094:ios:1c88a687a0210406c11e9f',
    messagingSenderId: '735124966094',
    projectId: 'tasky-app-e793e',
    storageBucket: 'tasky-app-e793e.firebasestorage.app',
    iosBundleId: 'com.example.taskyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB97okaEyeJW8h_KAOUSbNRNC9nHVje_o',
    appId: '1:735124966094:ios:1c88a687a0210406c11e9f',
    messagingSenderId: '735124966094',
    projectId: 'tasky-app-e793e',
    storageBucket: 'tasky-app-e793e.firebasestorage.app',
    iosBundleId: 'com.example.taskyApp',
  );
}
